# This file was generated by GoReleaser. DO NOT EDIT.
cask "poli" do
  name "poli"
  desc "Terminal-based HTTP client — collections, requests, curl import, zero lag."
  homepage "https://github.com/jojipanackal/poli"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poli"

  on_macos do
    on_intel do
      url "https://github.com/jojipanackal/poli/releases/download/v#{version}/poli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/jojipanackal/poli"
      sha256 "f0bbf8692ceb0ba3a52a433e2285ae602e2b65a7ae46054c757723ed727d895a"
    end
    on_arm do
      url "https://github.com/jojipanackal/poli/releases/download/v#{version}/poli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/jojipanackal/poli"
      sha256 "e7e293abc906f58ef3d80b51f8cedb11a5f20d3458f27e0d7db5c2055bc3f1aa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jojipanackal/poli/releases/download/v#{version}/poli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/jojipanackal/poli"
      sha256 "7dac8df60c12d51f7c20bb23550d5c34539372f662d6f1ea54434a13680c7cb2"
    end
    on_arm do
      url "https://github.com/jojipanackal/poli/releases/download/v#{version}/poli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/jojipanackal/poli"
      sha256 "a91844be0f34f97ccb2662811d342e2eed2e58ee89ae5756bf93dee120c0a1b5"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poli"]
    system_command "#{staged_path}/poli", args: ["version"]
  end

  caveats do
    "Get started:"
    "  poli new group \"My APIs\""
    "  poli new \"Get Users\" --url https://jsonplaceholder.typicode.com/users"
    "  poli ping r1"
    ""
    "Run 'poli help' for all commands."
  end

  # No zap stanza required
end
