# This file was generated by GoReleaser. DO NOT EDIT.
cask "poli" do
  name "poli"
  desc "Terminal-based HTTP client — collections, requests, curl import, zero lag."
  homepage "https://github.com/jojipanackal/poli"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poli"
  bash_completion "poli.bash"
  zsh_completion "poli.zsh"
  fish_completion "poli.fish"

  on_macos do
    on_intel do
      url "https://github.com/jojipanackal/poli/releases/download/v#{version}/poli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/jojipanackal/poli"
      sha256 "d16b7ef9b6e9262f34a0efbe513edf7cb22e0f5963210f1943a0e1f9348c5fc1"
    end
    on_arm do
      url "https://github.com/jojipanackal/poli/releases/download/v#{version}/poli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/jojipanackal/poli"
      sha256 "02041e60965d9fc51ad60a3e43f8ab206313c3d3a41b62291f6712833c0c8ee5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jojipanackal/poli/releases/download/v#{version}/poli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/jojipanackal/poli"
      sha256 "a331e3f6010115e5081ee1ffcfefcf2b7f7edc31eb266f9eb70e19aaef146521"
    end
    on_arm do
      url "https://github.com/jojipanackal/poli/releases/download/v#{version}/poli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/jojipanackal/poli"
      sha256 "fdd77884f33040e622d25983952d524e101a720fcf6e85df79e795ea06ab6a72"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poli"]
    system_command "#{staged_path}/poli", args: ["version"]
  end

  caveats do
    "Get started:"
    "  poli new group \"My APIs\""
    "  poli new \"Get Users\" --url https://jsonplaceholder.typicode.com/users"
    "  poli ping r1"
    ""
    "Run 'poli help' for all commands."
  end

  # No zap stanza required
end
