# This file was generated by GoReleaser. DO NOT EDIT.
cask "poli" do
  name "poli"
  desc "Terminal-based HTTP client — collections, requests, curl import, zero lag."
  homepage "https://github.com/jojipanackal/poli"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poli"
  bash_completion "poli.bash"
  zsh_completion "poli.zsh"
  fish_completion "poli.fish"

  on_macos do
    on_intel do
      url "https://github.com/jojipanackal/poli/releases/download/v#{version}/poli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/jojipanackal/poli"
      sha256 "af55af6efb193450016ed4cce9deac90827c8e51f1cbbc6f70e8bdc7c1ad8f2d"
    end
    on_arm do
      url "https://github.com/jojipanackal/poli/releases/download/v#{version}/poli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/jojipanackal/poli"
      sha256 "f9d4be47aab0eb15fba30c785ca097deaf597a5fb3be5b371e787c05bae8cf13"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jojipanackal/poli/releases/download/v#{version}/poli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/jojipanackal/poli"
      sha256 "a1a66d9698f4fa11f27362b6822bcecb8611acba46ebb7d3f363877caad490dc"
    end
    on_arm do
      url "https://github.com/jojipanackal/poli/releases/download/v#{version}/poli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/jojipanackal/poli"
      sha256 "fdb80d122b6b9919baa55619705436e90868a1d048f481e8c49f153e5775e9e4"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poli"]
    system_command "#{staged_path}/poli", args: ["version"]
  end

  caveats do
    "Get started:"
    "  poli new group \"My APIs\""
    "  poli new \"Get Users\" --url https://jsonplaceholder.typicode.com/users"
    "  poli ping r1"
    ""
    "Run 'poli help' for all commands."
  end

  # No zap stanza required
end
